title: 李 欧
position: 杭州师范大学
affiliation: 阿里巴巴商学院
email: yourname (at) example.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/
linkedin: https://www.linkedin.com/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
